# Generated by Django 3.2.20 on 2023-07-11 14:41

from django.db import migrations, models


def assign_attributes_to_products(apps, schema_editor):
    AttributeProduct = apps.get_model("attribute", "AttributeProduct")

    for attribute_product in AttributeProduct.objects.all():
        for product in attribute_product.assigned_products.all():
            attribute = attribute_product.attribute

            # Check if this attribute hasn't already been added
            if product.new_attributes.filter(attributes=attribute).exists():
                continue

            product.new_attributes.add(attribute)
            product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0029_alter_attribute_unit"),
        ("product", "0185_unmount_product_charge_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="new_products", to="attribute.Attribute"
            ),
        ),
        migrations.RunPython(assign_attributes_to_products),
        migrations.RemoveField(
            model_name="product",
            name="new_attributes",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="attribute.Attribute"
            ),
        ),
    ]
