# Generated by Django 3.2.20 on 2023-08-04 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0187_product_new_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="attributes",
        ),
    ]
