# Generated by Django 3.2.20 on 2023-07-18 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0186_product_new_attributes"),
        ("attribute", "0030_assignedproductattributevalue_new_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignedproductattributevalue",
            old_name="new_product",
            new_name="product",
        ),
        migrations.AlterUniqueTogether(
            name="assignedproductattributevalue",
            unique_together={("value", "product")},
        ),
    ]
